#!/usr/bin/env bash
# a Bash script that configures nginx in a new Ubuntu machin


sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
