#!/usr/bin/env bash
# a Bash script that configures nginx in a new Ubuntu machine


sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html

string="\n\tlocation /redirect_me { \n\t\trewrite \^/redirect_me\$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t\}"
sudo sed -i "/\tlisten \[::\]:80 default_server;/a\\$string" example.com

sudo nginx -t
sudo service nginx restart
