#!/usr/bin/env bash
# A bash script that displays
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
}
# Trap SIGTERM signal and call handle_sigterm function
trap handle_sigterm SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
